### ISSUE TITLE
Let me write stuff dynamically

### ISSUE THREAD

**Issue by tylerjnorton** [acoll/trivia#12]
So, when I want to write a message as the "please wait" message or whatever, I want to be able to write "Round [round#] and question [question#] and have it display the right data. Is that possible?

**Comment by cannjeff** [comment]
I've got this working, but there is a really limited amount of data available to inject.

Currently all you'll have access to is:
round number - [#roundNum]
round points - [#points]

**Comment by tylerjnorton** [comment]
Team name that buzzed in.
